### ISSUE TITLE
Travis build broken

### ISSUE THREAD

**Issue by jbmcewan** [jbmcewan/starwars-names#3]
$ npm install 
npm ERR! install Couldn't read dependencies
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v4.3.2/bin/node" "/home/travis/.nvm/versions/node/v4.3.2/bin/npm" "install"
npm ERR! node v4.3.2
npm ERR! npm  v2.14.21
npm ERR! file /home/travis/build/jbmcewan/starwars-names/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '<' at 2:1
npm ERR! <<<<<<< HEAD
npm ERR! ^
npm ERR! File: /home/travis/build/jbmcewan/starwars-names/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/jbmcewan/starwars-names/npm-debug.log

**Comment by jbmcewan** [comment]
$ npm run coverage-generate

> jbm-starwars-names@0.0.0-semantically-released coverage-generate /home/travis/build/jbmcewan/starwars-names

> babel-node --presets es2015 ./node_modules/.bin/isparta cover ./node_modules/.bin/_mocha -- --compilers js:babel-core/register

module.js:327

    throw err;

    ^

Error: Cannot find module '/home/travis/build/jbmcewan/starwars-names/node_modules/.bin/isparta'

    at Function.Module._resolveFilename (module.js:325:15)

    at Function.Module._load (module.js:276:25)

    at Function.Module.runMain (module.js:441:10)

    at /home/travis/build/jbmcewan/starwars-names/node_modules/babel-cli/lib/_babel-node.js:161:27

    at Object.<anonymous> (/home/travis/build/jbmcewan/starwars-names/node_modules/babel-cli/lib/_babel-node.js:162:7)

    at Module._compile (module.js:409:26)

    at Object.Module._extensions..js (module.js:416:10)

    at Module.load (module.js:343:32)

    at Function.Module._load (module.js:300:12)

    at Function.Module.runMain (module.js:441:10)
